### ISSUE TITLE
Could not find field '('gas', 'mass')'

### ISSUE THREAD

**Issue by yzhenggit** [trident-project/trident#122]
Hi, I'm doing a simple `trident.add_ion_fields(ds,ion_list) `, but the code (version 1.3.dev1) is giving me a bug saying `YTFieldNotFound: Could not find field '('gas', 'mass')' in DD2175.` Not sure what's going on, but seems like `mass` should be `cell_mass` instead? Could you help to fix it? Thank you!

**Comment by chummels** [comment]
I think the issue is that you're using trident's development version with the wrong version of yt.  Trident's dev version requires the yt-4.0 branch of yt, so that it works with particle-based datasets.  We recently had to move ('gas', 'cell_mass') to ('gas', 'mass') to deal with non-grid-based datasets.  But the above is automatically aliased in yt-4.0.  Make sure you have the git repo of yt installed, then:

cd <yt dir>
git checkout yt-4.0
pip install -e .

Looks like our installation instructions need updating since the last release.  Let me know if this helps.

**Comment by yzhenggit** [comment]
Thanks Cameron! Yes, updating to yt-4.0 fixes the issue.
